"""Initial migration

Revision ID: 13eb233f0880
Revises: 
Create Date: 2025-09-13 01:22:57.522641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13eb233f0880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(
            sa.Column('location', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        op.add_column('user', sa.Column('username', sa.String(
            length=80), nullable=False, server_default='temp_user'))
        batch_op.add_column(sa.Column('profile_picture',
                            sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('username')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('created_at')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
